dist: trusty
sudo: required

language: cpp

compiler:
  - gcc
  # - clang

addons:
 apt:
  sources:
   - boost-latest
   - ubuntu-toolchain-r-test
   - sourceline: deb http://us.archive.ubuntu.com/ubuntu/ xenial main universe
  packages:
   - g++
   - libboost-all-dev
   - wget
   - libcpprest-dev

cache:
 - apt

install:
  - wget https://dl.influxdata.com/influxdb/releases/influxdb-1.2.4_linux_amd64.tar.gz
  - tar xvfz influxdb-1.2.4_linux_amd64.tar.gz

script:
  - cd ${TRAVIS_BUILD_DIR}
  - make -C build/linux/gmake config=release_x64
  - /bin/bash -c "./src/script/test.sh bin/linux/gmake/x64/Release"
